# Generated by Django 5.0.7 on 2024-07-20 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of post.', max_length=200)),
                ('content', models.TextField(help_text='Content of post.', max_length=500)),
                ('published_date', models.DateTimeField(auto_now_add=True, help_text='Published date of post.')),
                ('author', models.ForeignKey(help_text='Author of post.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='Author of comment.', max_length=100)),
                ('text', models.TextField(help_text='Content of comment.', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Created date of comment.')),
                ('post', models.ForeignKey(help_text='Post of comment.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog_app.post')),
            ],
        ),
    ]
